### ISSUE TITLE
Did you find the way to read janusgraph data to spark RDD?

### ISSUE THREAD

**Issue by fengfst** [semi-technologies/janus-spark-analytics#6]
Did you find the way to read janusgraph data to spark RDD?

**Comment by etiennedi** [comment]
Hello @fengfst 

This application is a helper service for https://github.com/creativesoftwarefdn/weaviate which in turn can use Janusgraph as one of its database connectors. This application aims to trigger spark jobs from Janusgraph data and then write the results in the cache. However, this is only required because our consuming application (`weaviate`) is written in Golang and we are currently forced to use the HTTP api to communicate with Spark.

If you are already using Janusgraph from an application that directly supports the [Tinkerpop Language Variants](http://tinkerpop.apache.org/docs/current/tutorials/gremlin-language-variants/), like Java for example, there's no need for this separate app. You can simply follow the approach [outlined in the Janus docs for Spark](https://docs.janusgraph.org/latest/hadoop-tp3.html#_olap_traversals_with_spark_standalone_cluster).

Please also take a look at [weaviate](https://github.com/creativesoftwarefdn/weaviate), it's an easy to use knowledge-graph tool that uses pluggable connectors. One such connector is Janusgraph. Depending on your use case it might be easier for you to use weaviate instead of Janusgraph directly.

Closing this issues as it's not an issue with this particular app. For questions specific to weaviate you can also use StackOverflow, for general questions around Janusgraph, the [Janusgraph mailing list](https://groups.google.com/forum/#!forum/janusgraph-users) is a great help.
